[package]
name = "apollo3-hal"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambiq-apollo3-pac = "0.1.0"
cortex-m = "0.7.3"
embedded-hal = "0.2.6"
