[tasks.build]
command = "cargo"
args = ["build", "--target", "thumbv7em-none-eabihf", "${@}"]

[tasks.flash]
command = "python"
#args = ["../tools/svl/svl.py", "-f", "target/thumbv7em-none-eabihf/release/sby-buoy", "/dev/ttyUSB0", "-v"]
args = ["../tools/svl/svl.py", "-f", "target/sby-buoy.bin", "/dev/ttyUSB0", "-v"]
dependencies = ["build"]

#[tasks.com]
#command = "picocom"
#args = ["-b",


[tasks.size]
command = "cargo"
args = ["size", "--bin", "sby-buoy", "--release", "--", "-A"]

[tasks.readobj]
command = "cargo"
args = ["readobj", "--bin", "sby-buoy", "--", "-h"]
