[tasks.build]
command = "cargo"
args = ["build", "--target", "thumbv7em-none-eabihf", "${@}"]

[tasks.copy]
command = "cargo"
args = ["objcopy", "${@}", "--", "-O", "binary", "target/sby-buoy.bin"]
dependencies = ["build"]

[tasks.flash]
command = "python"
args = ["../tools/svl/svl.py", "-f", "target/sby-buoy.bin", "/dev/ttyUSB0", "-v"]
dependencies = ["build", "copy"]

[tasks.com]
command = "picocom"
args = ["/dev/ttyUSB0"]

[tasks.size]
command = "cargo"
args = ["size", "--", "-A"]

[tasks.readobj]
command = "cargo"
args = ["readobj", "--bin", "sby-buoy", "--", "-h"]
